language: python
python:
  - "3.6"
  - "3.5"
  
# Command to install dependancies
install: "make"
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - coverage run -m tests
after_success:
  - coveralls

after_script:
  - coveralls 

