language: python

python:
  -"2.7" 
   
# Command to install dependancies
install:
  -pip install -r requirements.txt
  

# command to run tests
script:
  -pytest 

after_success:
  -coveralls

after_script:
  -coveralls 





